# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

    #   The user confirms their input by typing `END` and Enter
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )

    #Auto increase build version
      gradle(task: "doIncreaseVersion")

    # Build the Debug variant
      build_android_app(task: "assembleDebug")

    crashlytics(
      api_token: '',
      build_secret: '',
      notes: changelog
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
